### ISSUE TITLE
Examples not working: TextAnnotationReader not found

### ISSUE THREAD

**Issue by pastoref** [CogComp/cogcomp-nlp#463]
Dear all,

I'm trying to run the following command

 scripts/runPipelineOnDataset.sh  config/pipelineConfig.txt input.txt output.txt

with input.txt being a file with some text (a sentence).

But I get the following message:

Exception in thread "main" java.lang.NoClassDefFoundError: edu/illinois/cs/cogcomp/nlp/corpusreaders/TextAnnotationReader
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3040)
	at java.lang.Class.getMethod0(Class.java:3010)
	at java.lang.Class.getMethod(Class.java:1776)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: edu.illinois.cs.cogcomp.nlp.corpusreaders.TextAnnotationReader
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

**Comment by pastoref** [comment]
My fault, I had compiling errors, to compile properly howerev I had to execute:

mvn install -Dmaven.test.skip=true -Dlicense.skip=true


because I had both test failures and licence issues.




Also, I had to execute

scripts/runPipelineOnDataset.sh  config/pipeline-config.properties input.txt output.txt

please note that the name of the config file is different than in the README


However I have issues:

Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [1.7 sec].
Downloading the folder from datastore . . . 
		GroupId: readonly.org.cogcomp.gazetteers
		ArtifactId: 1.5/gazetteers.zip
The target /home/users/fpastore/.cogcomp-datastore/readonly.org.cogcomp.gazetteers/1.5/gazetteers already exists. Skipping download from the datastore . . . 
java.io.FileNotFoundException: /home/users/fpastore/.cogcomp-datastore/readonly.org.cogcomp.gazetteers/1.5/gazetteers/gazetteers/gazetteers-list.txt (No such file or directory)

**Comment by mssammon** [comment]
Thank you for reporting these problems.
We have had a machine outage that affected a server we are using to host some dependency data -- from the error you report, it looks like the data server has not yet been restored.  We are investigating the problem and will update this thread when we know more.

**Comment by danyaljj** [comment]
@pastoref could you do this and report the results for me? 
Go to your home folder and deleted these hidden folders: `.cogcomp-datastore` and `.cogcomp-datastore-tmp`. 
And then re-run your program.

**Comment by pastoref** [comment]
Seems the issue is still there. Do I have to update the code? Where is it supposed to connect? Should I check if tehre is some firewall blocking the connection?

`15:43:26 INFO  SLModel:97 - Load Model complete!
15:43:26 INFO  LabeledChuLiuEdmondsDecoder:72 - Loading cached PoS-to-dep dictionary from deprels.dict
Reading POS tagger model from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [2.6 sec].
Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [1.9 sec].
Downloading the folder from datastore . . . 
		GroupId: readonly.org.cogcomp.gazetteers
		ArtifactId: 1.5/gazetteers.zip
augmentedGroupId: readonly.org.cogcomp.gazetteers
versionedFileName: 1.5/gazetteers.zip
zippedFileName: /home/users/fpastore/.cogcomp-datastore-tmp/gazetteers.zip
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.squareup.okhttp.internal.Platform.connectSocket(Platform.java:101)
	at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:137)
	at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:108)
	at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
	at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	at com.squareup.okhttp.Call.getResponse(Call.java:286)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.execute(Call.java:80)
	at io.minio.MinioClient.execute(MinioClient.java:826)
	at io.minio.MinioClient.executeHead(MinioClient.java:1018)
	at io.minio.MinioClient.statObject(MinioClient.java:1154)
	at io.minio.MinioClient.getObject(MinioClient.java:1343)
	at org.cogcomp.Datastore.getDirectory(Datastore.java:401)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.init(TreeGazetteers.java:64)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.<init>(TreeGazetteers.java:50)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.GazetteersFactory.init(GazetteersFactory.java:54)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readAndLoadConfig(Parameters.java:312)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readConfigAndLoadExternalData(Parameters.java:57)
	at edu.illinois.cs.cogcomp.ner.NERAnnotator.initialize(NERAnnotator.java:103)
	at edu.illinois.cs.cogcomp.annotation.Annotator.doInitialize(Annotator.java:125)
	at edu.illinois.cs.cogcomp.annotation.Annotator.lazyAddView(Annotator.java:179)
	at edu.illinois.cs.cogcomp.annotation.Annotator.getView(Annotator.java:166)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.addView(BasicAnnotatorService.java:331)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.addView(BasicAnnotatorService.java:328)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.addViewsAndCache(BasicAnnotatorService.java:375)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.createAnnotatedTextAnnotation(BasicAnnotatorService.java:353)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.createAnnotatedTextAnnotation(BasicAnnotatorService.java:202)
	at edu.illinois.cs.cogcomp.pipeline.main.RunPipeline.RunPipelineOnFile(RunPipeline.java:107)
	at edu.illinois.cs.cogcomp.pipeline.main.RunPipeline.main(RunPipeline.java:92)
java.io.FileNotFoundException: /home/users/fpastore/.cogcomp-datastore-tmp/gazetteers.zip (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.cogcomp.ZipHelper.unZipIt(ZipHelper.java:71)
	at org.cogcomp.Datastore.getDirectory(Datastore.java:432)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.init(TreeGazetteers.java:64)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.<init>(TreeGazetteers.java:50)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.GazetteersFactory.init(GazetteersFactory.java:54)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readAndLoadConfig(Parameters.java:312)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readConfigAndLoadExternalData(Parameters.java:57)
	at edu.illinois.cs.cogcomp.ner.NERAnnotator.initialize(NERAnnotator.java:103)
	at edu.illinois.cs.cogcomp.annotation.Annotator.doInitialize(Annotator.java:125)
	at edu.illinois.cs.cogcomp.annotation.Annotator.lazyAddView(Annotator.java:179)
	at edu.illinois.cs.cogcomp.annotation.Annotator.getView(Annotator.java:166)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.addView(BasicAnnotatorService.java:331)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.addView(BasicAnnotatorService.java:328)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.addViewsAndCache(BasicAnnotatorService.java:375)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.createAnnotatedTextAnnotation(BasicAnnotatorService.java:353)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.createAnnotatedTextAnnotation(BasicAnnotatorService.java:202)
	at edu.illinois.cs.cogcomp.pipeline.main.RunPipeline.RunPipelineOnFile(RunPipeline.java:107)
	at edu.illinois.cs.cogcomp.pipeline.main.RunPipeline.main(RunPipeline.java:92)
zippedFileName: /home/users/fpastore/.cogcomp-datastore-tmp/gazetteers.zip
path: /home/users/fpastore/.cogcomp-datastore/readonly.org.cogcomp.gazetteers/1.5/gazetteers
artifactId: gazetteers
java.io.FileNotFoundException: /home/users/fpastore/.cogcomp-datastore/readonly.org.cogcomp.gazetteers/1.5/gazetteers/gazetteers/gazetteers-list.txt (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.init(TreeGazetteers.java:67)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.<init>(TreeGazetteers.java:50)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.GazetteersFactory.init(GazetteersFactory.java:54)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readAndLoadConfig(Parameters.java:312)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readConfigAndLoadExternalData(Parameters.java:57)
	at edu.illinois.cs.cogcomp.ner.NERAnnotator.initialize(NERAnnotator.java:103)
	at edu.illinois.cs.cogcomp.annotation.Annotator.doInitialize(Annotator.java:125)
	at edu.illinois.cs.cogcomp.annotation.Annotator.lazyAddView(Annotator.java:179)
	at edu.illinois.cs.cogcomp.annotation.Annotator.getView(Annotator.java:166)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.addView(BasicAnnotatorService.java:331)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.addView(BasicAnnotatorService.java:328)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.addViewsAndCache(BasicAnnotatorService.java:375)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.createAnnotatedTextAnnotation(BasicAnnotatorService.java:353)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.createAnnotatedTextAnnotation(BasicAnnotatorService.java:202)
	at edu.illinois.cs.cogcomp.pipeline.main.RunPipeline.RunPipelineOnFile(RunPipeline.java:107)
	at edu.illinois.cs.cogcomp.pipeline.main.RunPipeline.main(RunPipeline.java:92)
Model file /mnt/gaiagpfs/users/homedirs/fpastore/cogcomp-nlp/pipeline/ner/models/CoNLL.model.level1 located in a jar file
Model file /mnt/gaiagpfs/users/homedirs/fpastore/cogcomp-nlp/pipeline/ner/models/CoNLL.model.level2 located in a jar file
15:43:49 ERROR NERAnnotator:161 - Cannot annotate the text, the exception was: 
java.lang.NullPointerException
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.ExpressiveFeaturesAnnotator.annotate(ExpressiveFeaturesAnnotator.java:73)
	at edu.illinois.cs.cogcomp.ner.NERAnnotator.addView(NERAnnotator.java:158)
	at edu.illinois.cs.cogcomp.annotation.Annotator.lazyAddView(Annotator.java:181)
	at edu.illinois.cs.cogcomp.annotation.Annotator.getView(Annotator.java:166)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.addView(BasicAnnotatorService.java:331)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.addView(BasicAnnotatorService.java:328)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.addViewsAndCache(BasicAnnotatorService.java:375)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.createAnnotatedTextAnnotation(BasicAnnotatorService.java:353)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.createAnnotatedTextAnnotation(BasicAnnotatorService.java:202)
	at edu.illinois.cs.cogcomp.pipeline.main.RunPipeline.RunPipelineOnFile(RunPipeline.java:107)
	at edu.illinois.cs.cogcomp.pipeline.main.RunPipeline.main(RunPipeline.java:92)
Exception in thread "main" java.lang.IllegalArgumentException: View NER_CONLL not found
	at edu.illinois.cs.cogcomp.core.datastructures.textannotation.AbstractTextAnnotation.getView(AbstractTextAnnotation.java:134)
	at edu.illinois.cs.cogcomp.annotation.Annotator.getView(Annotator.java:167)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.addView(BasicAnnotatorService.java:331)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.addView(BasicAnnotatorService.java:328)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.addViewsAndCache(BasicAnnotatorService.java:375)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.createAnnotatedTextAnnotation(BasicAnnotatorService.java:353)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.createAnnotatedTextAnnotation(BasicAnnotatorService.java:202)
	at edu.illinois.cs.cogcomp.pipeline.main.RunPipeline.RunPipelineOnFile(RunPipeline.java:107)
	at edu.illinois.cs.cogcomp.pipeline.main.RunPipeline.main(RunPipeline.java:92)
scripts/runPipelineOnDataset.sh: done.`

**Comment by danyaljj** [comment]
Are you sure you don't have any internet connection problems?
