### ISSUE TITLE
MapDB annotator caching in parallel 

### ISSUE THREAD

**Issue by danyaljj** [CogComp/cogcomp-nlp#484]
I just tried to use an annotator and it failed (at least) because of MapDB issues. 
We should test this and have proper instructions on how to parallelize cached annotators.

**Comment by mssammon** [comment]
Can you give a more detailed description so we can generate a test case?

**Comment by danyaljj** [comment]
Here is an example (in Scala, because it is easy to parallelize things): 

This works because it is sequential: 
```scala 
        val pipelineServerClient = {
          val x = new ServerClientAnnotator()
          x.setUrl("http://austen.cs.illinois.edu", "5800")
          //x.setViewsAll(viewsToAdd.toArray)
          x.useCaching("testDB.cache")
          x
        }
        val p = "On one particularly cold night in Alaska back in December (it’s January now as I write this) I got bored and decided to write my own random string method. As I started to write the code, I realized there were several different ways to tackle the problem. For me this is a cool thing about Scala; it’s like the old Perl slogan, “There’s more than one way to do it.”"
        (0 to 100).foreach{ idx =>
          println("idx = " + idx)
          val ta = pipelineServerClient.annotate(p.substring(0, Random.nextInt(p.length)))
        }
```

This gives exception because it is sequential and there is no locking on writing in the DB file: 
```
        lazy val pipelineServerClient = {
          val x = new ServerClientAnnotator()
          x.setUrl("http://austen.cs.illinois.edu", "5800")
          //x.setViewsAll(viewsToAdd.toArray)
          x.useCaching("testDB.cache")
          x
        }
        val p = "On one particularly cold night in Alaska back in December (it’s January now as I write this) I got bored and decided to write my own random string method. As I started to write the code, I realized there were several different ways to tackle the problem. For me this is a cool thing about Scala; it’s like the old Perl slogan, “There’s more than one way to do it.”"
        (0 to 100).par.foreach{ idx =>
          println("idx = " + idx)
          val ta = pipelineServerClient.annotate(p.substring(0, Random.nextInt(p.length)))
        }
```
Not that the difference between the two codes is in the ".par" operator, which makes a for-loop parallel (easy huh?). 
Here is the log of the exception: 
```
[info] idx = 4
[info] idx = 26
[info] idx = 1
[info] idx = 13
[info] idx = 19
[info] idx = 51
[info] idx = 16
[info] idx = 7
[info] idx = 52
[info] idx = 27
[info] idx = 5
[info] idx = 14
[info] idx = 21
[info] idx = 2
[info] idx = 53
[info] idx = 17
[info] idx = 8
[info] idx = 28
[info] idx = 75
[info] idx = 22
[info] idx = 9
[info] idx = 56
[info] idx = 31
[info] idx = 10
[info] idx = 62
[info] idx = 65
[info] idx = 68
[info] idx = 37
[info] idx = 76
[info] idx = 43
[info] idx = 78
[info] idx = 63
[info] idx = 69
[info] idx = 38
[info] idx = 71
[info] idx = 40
[info] idx = 66
[info] idx = 44
[info] idx = 46
[info] idx = 88
[info] idx = 81
[info] idx = 94
[info] idx = 95
[info] idx = 91
[info] idx = 92
[info] idx = 97
[info] idx = 89
[info] idx = 99
[error] Exception in thread "main" org.mapdb.DBException$VolumeIOError
[error] 	at org.mapdb.volume.RandomAccessFileVol.getPackedLong(RandomAccessFileVol.java:385)
[error] 	at org.mapdb.WriteAheadLog.walGetRecord(WriteAheadLog.java:849)
[error] 	at org.mapdb.StoreWAL$commit$4.value(StoreWAL.kt:583)
[error] 	at org.eclipse.collections.impl.map.mutable.primitive.LongLongHashMap.forEachKeyValue(LongLongHashMap.java:988)
[error] 	at org.mapdb.StoreWAL.commit(StoreWAL.kt:582)
[error] 	at org.mapdb.DB.commit(DB.kt:219)
[error] 	at edu.illinois.cs.cogcomp.pipeline.server.ServerClientAnnotator.annotate(ServerClientAnnotator.java:141)
[error] 	at org.allenai.ari.solvers.textilp.ExperimentsApp$$anonfun$main$21.apply$mcVI$sp(ExperimentsApp.scala:2195)
[error] 	at scala.collection.parallel.immutable.ParRange$ParRangeIterator.foreach(ParRange.scala:91)
[error] 	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:972)
[error] 	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
[error] 	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
[error] 	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
[error] 	at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
[error] 	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:969)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:169)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:443)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:149)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
[error] 	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
[error] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[error] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[error] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[error] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] Caused by: java.io.EOFException
[error] 	at java.io.RandomAccessFile.readByte(RandomAccessFile.java:669)
[error] 	at org.mapdb.volume.RandomAccessFileVol.getPackedLong(RandomAccessFileVol.java:379)
[error] 	... 23 more
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last root/compile:run for the full output.
[error] (root/compile:run) Nonzero exit code returned from runner: 1
[error] Total time: 15 s, completed Jun 22, 2017 3:43:08 PM
```
