### ISSUE TITLE
NER gazetteer

### ISSUE THREAD

**Issue by mortezakz** [CogComp/cogcomp-nlp#506]
Trying to run your latest version NER, 3.1.23, and this is the error I'm getting:

Downloading the folder from datastore . . . 
		GroupId: readonly.org.cogcomp.gazetteers
		ArtifactId: 1.5\gazetteers.zip
The target C:\Users\Morteza\.cogcomp-datastore\readonly.org.cogcomp.gazetteers\1.5\gazetteers already exists. Skipping download from the datastore . . . 
java.io.FileNotFoundException: C:\Users\Morteza\.cogcomp-datastore\readonly.org.cogcomp.gazetteers\1.5\gazetteers\gazetteers\gazetteers-list.txt (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.init(TreeGazetteers.java:67)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.<init>(TreeGazetteers.java:50)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.GazetteersFactory.init(GazetteersFactory.java:54)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readAndLoadConfig(Parameters.java:312)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readConfigAndLoadExternalData(Parameters.java:57)
	at edu.illinois.cs.cogcomp.ner.NERAnnotator.initialize(NERAnnotator.java:101)
	at edu.illinois.cs.cogcomp.annotation.Annotator.doInitialize(Annotator.java:125)
....
Model file E:\Codes\ner\models\CoNLL_enron.model.level1 located in a jar file
Model file E:\Codes\ner\models\CoNLL_enron.model.level2 located in a jar file
22:53:33.653 [main] ERROR e.i.cs.cogcomp.ner.NERAnnotator - Cannot annotate the text, the exception was: 
java.lang.NullPointerException: null
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.ExpressiveFeaturesAnnotator.annotate(ExpressiveFeaturesAnnotator.java:73) ~[illinois-ner-3.1.23.jar:na]
	at edu.illinois.cs.cogcomp.ner.NERAnnotator.addView(NERAnnotator.java:152) ~[illinois-ner-3.1.23.jar:na]
	..
Exception in thread "main" java.lang.IllegalArgumentException: View NER_CONLL not found
	at edu.illinois.cs.cogcomp.core.datastructures.textannotation.AbstractTextAnnotation.getView(AbstractTextAnnotation.java:134)
..

**Comment by mortezakz** [comment]
I deleted the folder, and instead got this:

Downloading the folder from datastore . . . 
		GroupId: readonly.org.cogcomp.gazetteers
		ArtifactId: 1.5\gazetteers.zip
augmentedGroupId: readonly.org.cogcomp.gazetteers
versionedFileName: 1.5\gazetteers.zip
zippedFileName: C:\Users\Morteza\.cogcomp-datastore-tmp\gazetteers.zip
error occured
ErrorResponse(code=InvalidURI, message=Couldn't parse the specified URI, bucketName=readonly.org.cogcomp.gazetteers, objectName=1.5\gazetteers.zip, resource=/readonly.org.cogcomp.gazetteers/1.5%5Cgazetteers.zip, requestId=14D24D4664C0CBE2, hostId=null)
request={method=HEAD, url=http://smaug.cs.illinois.edu:8080/readonly.org.cogcomp.gazetteers/1.5%5Cgazetteers.zip, headers=Host: smaug.cs.illinois.edu:8080
User-Agent: Minio (amd64; amd64) minio-java/dev
x-amz-date: 20170718T025628Z
}
response={code=400, headers=Accept-Ranges: bytes
Server: Minio/RELEASE.2017-03-16T21-50-32Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 14D24D4664C0CBE2
Date: Tue, 18 Jul 2017 02:56:30 GMT
Content-Type: text/plain; charset=utf-8
OkHttp-Sent-Millis: 1500346588897
OkHttp-Received-Millis: 1500346588972
}

	at io.minio.MinioClient.execute(MinioClient.java:922)
	at io.minio.MinioClient.executeHead(MinioClient.java:1018)
	at io.minio.MinioClient.statObject(MinioClient.java:1154)
	at io.minio.MinioClient.getObject(MinioClient.java:1343)
	at org.cogcomp.Datastore.getDirectory(Datastore.java:401)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.init(TreeGazetteers.java:64)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.<init>(TreeGazetteers.java:50)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.GazetteersFactory.init(GazetteersFactory.java:54)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readAndLoadConfig(Parameters.java:312)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readConfigAndLoadExternalData(Parameters.java:57)
	at edu.illinois.cs.cogcomp.ner.NERAnnotator.initialize(NERAnnotator.java:101)
	at edu.illinois.cs.cogcomp.annotation.Annotator.doInitialize(Annotator.java:125)
..
java.io.FileNotFoundException: C:\Users\Morteza\.cogcomp-datastore-tmp\gazetteers.zip (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.cogcomp.ZipHelper.unZipIt(ZipHelper.java:71)
	at org.cogcomp.Datastore.getDirectory(Datastore.java:432)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.init(TreeGazetteers.java:64)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.<init>(TreeGazetteers.java:50)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.GazetteersFactory.init(GazetteersFactory.java:54)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readAndLoadConfig(Parameters.java:312)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readConfigAndLoadExternalData(Parameters.java:57)
	at edu.illinois.cs.cogcomp.ner.NERAnnotator.initialize(NERAnnotator.java:101)
	at edu.illinois.cs.cogcomp.annotation.Annotator.doInitialize(Annotator.java:125)
..
zippedFileName: C:\Users\Morteza\.cogcomp-datastore-tmp\gazetteers.zip
path: C:\Users\Morteza\.cogcomp-datastore\readonly.org.cogcomp.gazetteers\1.5\gazetteers
artifactId: gazetteers
java.io.FileNotFoundException: C:\Users\Morteza\.cogcomp-datastore\readonly.org.cogcomp.gazetteers\1.5\gazetteers\gazetteers\gazetteers-list.txt (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.init(TreeGazetteers.java:67)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.<init>(TreeGazetteers.java:50)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.GazetteersFactory.init(GazetteersFactory.java:54)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readAndLoadConfig(Parameters.java:312)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readConfigAndLoadExternalData(Parameters.java:57)
	at edu.illinois.cs.cogcomp.ner.NERAnnotator.initialize(NERAnnotator.java:101)
	at edu.illinois.cs.cogcomp.annotation.Annotator.doInitialize(Annotator.java:125)
	..
Model file E:\Codes\ner\models\CoNLL_enron.model.level1 located in a jar file
Model file E:\Codes\ner\models\CoNLL_enron.model.level2 located in a jar file
22:56:32.029 [main] ERROR e.i.cs.cogcomp.ner.NERAnnotator - Cannot annotate the text, the exception was: 
java.lang.NullPointerException: null
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.ExpressiveFeaturesAnnotator.annotate(ExpressiveFeaturesAnnotator.java:73) ~[illinois-ner-3.1.23.jar:na]
	at edu.illinois.cs.cogcomp.ner.NERAnnotator.addView(NERAnnotator.java:152) ~[illinois-ner-3.1.23.jar:na]
..
Exception in thread "main" java.lang.IllegalArgumentException: View NER_CONLL not found
	at edu.illinois.cs.cogcomp.core.datastructures.textannotation.AbstractTextAnnotation.getView(AbstractTextAnnotation.java:134)
..

**Comment by danyaljj** [comment]
@Slash0BZ the recent changes you made should solve this; right?

**Comment by Slash0BZ** [comment]
@danyaljj Yes the latest commit solves this issue, and @mortezakz you have to delete the path "C:\Users\Morteza.cogcomp-datastore-tmp" and (if exists) "C:\Users\Morteza.cogcomp-datastore" again first and then use the latest datastore. Thanks

**Comment by danyaljj** [comment]
Well I'll have to send a pull request and upgrade datastore .... will let you know @mortezakz

**Comment by mortezakz** [comment]
@Slash0BZ  Thanks for the comment. I did delete those two folders, and didn't work. 
And thanks @danyaljj. Good luck with upgrading the datastore.

**Comment by danyaljj** [comment]
@mortezakz try version 3.1.24. 
And as @Slash0BZ said, you have to clean your cache before using it.

**Comment by mortezakz** [comment]
Deleted those two folders, and ran the latest version. Still doesn't work:

Downloading the folder from datastore . . . 
		GroupId: readonly.org.cogcomp.gazetteers
		ArtifactId: 1.5\gazetteers.zip
augmentedGroupId: readonly.org.cogcomp.gazetteers
versionedFileName: 1.5\gazetteers.zip
zippedFileName: C:\Users\Morteza\.cogcomp-datastore-tmp\gazetteers.zip
error occured
ErrorResponse(code=InvalidURI, message=Couldn't parse the specified URI, bucketName=readonly.org.cogcomp.gazetteers, objectName=1.5\gazetteers.zip, resource=/readonly.org.cogcomp.gazetteers/1.5%5Cgazetteers.zip, requestId=14D27A9D058A5D09, hostId=null)
request={method=HEAD, url=http://smaug.cs.illinois.edu:8080/readonly.org.cogcomp.gazetteers/1.5%5Cgazetteers.zip, headers=Host: smaug.cs.illinois.edu:8080
User-Agent: Minio (amd64; amd64) minio-java/dev
x-amz-date: 20170718T164718Z
}
response={code=400, headers=Accept-Ranges: bytes
Server: Minio/RELEASE.2017-03-16T21-50-32Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 14D27A9D058A5D09
Date: Tue, 18 Jul 2017 16:47:20 GMT
Content-Type: text/plain; charset=utf-8
OkHttp-Sent-Millis: 1500396439149
OkHttp-Received-Millis: 1500396439212
}

	at io.minio.MinioClient.execute(MinioClient.java:922)
	at io.minio.MinioClient.executeHead(MinioClient.java:1018)
	at io.minio.MinioClient.statObject(MinioClient.java:1154)
	at io.minio.MinioClient.getObject(MinioClient.java:1343)
	at org.cogcomp.Datastore.getDirectory(Datastore.java:401)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.init(TreeGazetteers.java:64)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.<init>(TreeGazetteers.java:50)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.GazetteersFactory.init(GazetteersFactory.java:54)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readAndLoadConfig(Parameters.java:312)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readConfigAndLoadExternalData(Parameters.java:57)
	at edu.illinois.cs.cogcomp.ner.NERAnnotator.initialize(NERAnnotator.java:101)
	at edu.illinois.cs.cogcomp.annotation.Annotator.doInitialize(Annotator.java:125)
..
java.io.FileNotFoundException: C:\Users\Morteza\.cogcomp-datastore-tmp\gazetteers.zip (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.cogcomp.ZipHelper.unZipIt(ZipHelper.java:71)
	at org.cogcomp.Datastore.getDirectory(Datastore.java:432)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.init(TreeGazetteers.java:64)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.<init>(TreeGazetteers.java:50)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.GazetteersFactory.init(GazetteersFactory.java:54)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readAndLoadConfig(Parameters.java:312)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readConfigAndLoadExternalData(Parameters.java:57)
	at edu.illinois.cs.cogcomp.ner.NERAnnotator.initialize(NERAnnotator.java:101)
	at edu.illinois.cs.cogcomp.annotation.Annotator.doInitialize(Annotator.java:125)
..
zippedFileName: C:\Users\Morteza\.cogcomp-datastore-tmp\gazetteers.zip
path: C:\Users\Morteza\.cogcomp-datastore\readonly.org.cogcomp.gazetteers\1.5\gazetteers
artifactId: gazetteers
java.io.FileNotFoundException: C:\Users\Morteza\.cogcomp-datastore\readonly.org.cogcomp.gazetteers\1.5\gazetteers\gazetteers\gazetteers-list.txt (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.init(TreeGazetteers.java:67)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.<init>(TreeGazetteers.java:50)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.GazetteersFactory.init(GazetteersFactory.java:54)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readAndLoadConfig(Parameters.java:312)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readConfigAndLoadExternalData(Parameters.java:57)
	at edu.illinois.cs.cogcomp.ner.NERAnnotator.initialize(NERAnnotator.java:101)
	at edu.illinois.cs.cogcomp.annotation.Annotator.doInitialize(Annotator.java:125)
..
Model file E:\Codes\ner\models\CoNLL_enron.model.level1 located in a jar file
Model file E:\Codes\ner\models\CoNLL_enron.model.level2 located in a jar file
12:47:22.449 [main] ERROR e.i.cs.cogcomp.ner.NERAnnotator - Cannot annotate the text, the exception was: 
java.lang.NullPointerException: null
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.ExpressiveFeaturesAnnotator.annotate(ExpressiveFeaturesAnnotator.java:73) ~[illinois-ner-3.1.24.jar:na]
	at edu.illinois.cs.cogcomp.ner.NERAnnotator.addView(NERAnnotator.java:152) ~[illinois-ner-3.1.24.jar:na]
..
Exception in thread "main" java.lang.IllegalArgumentException: View NER_CONLL not found
	at edu.illinois.cs.cogcomp.core.datastructures.textannotation.AbstractTextAnnotation.getView(AbstractTextAnnotation.java:134)
..

**Comment by danyaljj** [comment]
@Slash0BZ do you mind giving a try to the latest NER on your windows machine?

**Comment by Slash0BZ** [comment]
@danyaljj Just did, it works fine. I deleted the data folder, cleaned the project, upgraded pipeline to 3.1.24 and upgraded the data-store to 1.9.8, it successfully downloaded.

**Comment by danyaljj** [comment]
@Slash0BZ  Well 3.1.24 should already use 1.9.8. So no need to update it. Can you try it again, after removing 3.1.24 and 1.9.8 from your maven cache? (just to make sure you're not using a stale version). 

@mortezakz looks like we're not able to reproduce your issue. Give us a code on which we can reproduce the issue.

**Comment by Slash0BZ** [comment]
@danyaljj Oops I can reproduce the error after invalidating the cache. @mortezakz Sorry let me see what's going on.

**Comment by danyaljj** [comment]
@mortezakz Try 3.1.25

**Comment by mortezakz** [comment]
Thanks folks. @danyaljj @Slash0BZ  I can use 3.1.10 for now, which seems to be working fine. I tried 3.1.25 and got the following (now the viewname is also not found)

Downloading the folder from datastore . . . 
		GroupId: readonly.org.cogcomp.gazetteers
		ArtifactId: 1.5\gazetteers.zip
augmentedGroupId: readonly.org.cogcomp.gazetteers
versionedFileName: 1.5\gazetteers.zip
zippedFileName: C:\Users\Morteza\.cogcomp-datastore-tmp\gazetteers.zip
error occured
ErrorResponse(code=InvalidURI, message=Couldn't parse the specified URI, bucketName=readonly.org.cogcomp.gazetteers, objectName=1.5\gazetteers.zip, resource=/readonly.org.cogcomp.gazetteers/1.5%5Cgazetteers.zip, requestId=14D27E14F7CF03C3, hostId=null)
request={method=HEAD, url=http://smaug.cs.illinois.edu:8080/readonly.org.cogcomp.gazetteers/1.5%5Cgazetteers.zip, headers=Host: smaug.cs.illinois.edu:8080
User-Agent: Minio (amd64; amd64) minio-java/dev
x-amz-date: 20170718T175052Z
}
response={code=400, headers=Accept-Ranges: bytes
Server: Minio/RELEASE.2017-03-16T21-50-32Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 14D27E14F7CF03C3
Date: Tue, 18 Jul 2017 17:50:54 GMT
Content-Type: text/plain; charset=utf-8
OkHttp-Sent-Millis: 1500400252821
OkHttp-Received-Millis: 1500400252885
}

	at io.minio.MinioClient.execute(MinioClient.java:922)
	at io.minio.MinioClient.executeHead(MinioClient.java:1018)
	at io.minio.MinioClient.statObject(MinioClient.java:1154)
	at io.minio.MinioClient.getObject(MinioClient.java:1343)
	at org.cogcomp.Datastore.getDirectory(Datastore.java:401)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.init(TreeGazetteers.java:64)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.<init>(TreeGazetteers.java:50)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.GazetteersFactory.init(GazetteersFactory.java:54)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readAndLoadConfig(Parameters.java:312)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readConfigAndLoadExternalData(Parameters.java:57)
	at edu.illinois.cs.cogcomp.ner.NERAnnotator.initialize(NERAnnotator.java:101)
	at edu.illinois.cs.cogcomp.annotation.Annotator.doInitialize(Annotator.java:125)
..
java.io.FileNotFoundException: C:\Users\Morteza\.cogcomp-datastore-tmp\gazetteers.zip (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.cogcomp.ZipHelper.unZipIt(ZipHelper.java:71)
	at org.cogcomp.Datastore.getDirectory(Datastore.java:432)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.init(TreeGazetteers.java:64)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.<init>(TreeGazetteers.java:50)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.GazetteersFactory.init(GazetteersFactory.java:54)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readAndLoadConfig(Parameters.java:312)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readConfigAndLoadExternalData(Parameters.java:57)
	at edu.illinois.cs.cogcomp.ner.NERAnnotator.initialize(NERAnnotator.java:101)
	at edu.illinois.cs.cogcomp.annotation.Annotator.doInitialize(Annotator.java:125)
..
zippedFileName: C:\Users\Morteza\.cogcomp-datastore-tmp\gazetteers.zip
path: C:\Users\Morteza\.cogcomp-datastore\readonly.org.cogcomp.gazetteers\1.5\gazetteers
artifactId: gazetteers
java.io.FileNotFoundException: C:\Users\Morteza\.cogcomp-datastore\readonly.org.cogcomp.gazetteers\1.5\gazetteers\gazetteers\gazetteers-list.txt (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.init(TreeGazetteers.java:67)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.<init>(TreeGazetteers.java:50)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.GazetteersFactory.init(GazetteersFactory.java:54)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readAndLoadConfig(Parameters.java:312)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readConfigAndLoadExternalData(Parameters.java:57)
	at edu.illinois.cs.cogcomp.ner.NERAnnotator.initialize(NERAnnotator.java:101)
	at edu.illinois.cs.cogcomp.annotation.Annotator.doInitialize(Annotator.java:125)
..
Model file E:\Codes\ner\models\CoNLL_enron.model.level1 located in a jar file
Model file E:\Codes\ner\models\CoNLL_enron.model.level2 located in a jar file
13:50:56.111 [main] ERROR e.i.cs.cogcomp.ner.NERAnnotator - Cannot annotate the text, the exception was: 
java.lang.NullPointerException: null
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.ExpressiveFeaturesAnnotator.annotate(ExpressiveFeaturesAnnotator.java:73) ~[illinois-ner-3.1.24.jar:na]
	at edu.illinois.cs.cogcomp.ner.NERAnnotator.addView(NERAnnotator.java:152) ~[illinois-ner-3.1.24.jar:na]
..
Exception in thread "main" java.lang.IllegalArgumentException: View NER_CONLL not found
	at edu.illinois.cs.cogcomp.core.datastructures.textannotation.AbstractTextAnnotation.getView(AbstractTextAnnotation.java:134)
..

**Comment by danyaljj** [comment]
Well we tried this 3.1.25 on our Windows machine and it seems to be working fine.  Would be great if you give it another try, after removing your datastore caches: 
 - "C:\Users\Morteza.cogcomp-datastore"
 - "C:\Users\Morteza.cogcomp-datastore-tmp"

**Comment by mortezakz** [comment]
Thanks. I did try  3.1.25 but got the error above which I posted in my last comment. I did try again, this time also deleting my ivy cache, and it seems to be working fine (but on a side note, it's even slower to load compared to 3.1.0).
Thanks guys.

**Comment by danyaljj** [comment]
It's expected to be slow the first time, but the 2nd try should be fine.
