### ISSUE TITLE
Failing pipeline:SentencePipelineTest

### ISSUE THREAD

**Issue by Slash0BZ** [CogComp/cogcomp-nlp#523]
The "testSentencePipeline" in the "SentencePipelineTest" https://github.com/CogComp/cogcomp-nlp/blob/master/pipeline/src/test/java/edu/illinois/cs/cogcomp/pipeline/main/SentencePipelineTest.java#L89 leads to an assertion error "java.lang.AssertionError: Expecting token: The, found 
Th instead." at https://github.com/CogComp/cogcomp-nlp/blob/master/core-utilities/src/main/java/edu/illinois/cs/cogcomp/core/datastructures/textannotation/TreeView.java#L543

**Comment by Slash0BZ** [comment]
Full trace output: 

java.lang.AssertionError: Expecting token: The, found 
Th instead.

	at edu.illinois.cs.cogcomp.core.datastructures.textannotation.TreeView.addParseTree(TreeView.java:543)
	at edu.illinois.cs.cogcomp.core.datastructures.textannotation.TreeView.addParseTree(TreeView.java:549)
	at edu.illinois.cs.cogcomp.core.datastructures.textannotation.TreeView.addParseTree(TreeView.java:549)
	at edu.illinois.cs.cogcomp.core.datastructures.textannotation.TreeView.addParseTree(TreeView.java:549)
	at edu.illinois.cs.cogcomp.core.datastructures.textannotation.TreeView.setParseTree(TreeView.java:265)
	at edu.illinois.cs.cogcomp.pipeline.handlers.StanfordParseHandler.addView(StanfordParseHandler.java:215)
	at edu.illinois.cs.cogcomp.annotation.Annotator.lazyAddView(Annotator.java:181)
	at edu.illinois.cs.cogcomp.annotation.Annotator.getView(Annotator.java:166)
	at edu.illinois.cs.cogcomp.pipeline.main.SentencePipeline.processBySentence(SentencePipeline.java:112)
	at edu.illinois.cs.cogcomp.pipeline.main.SentencePipeline.addView(SentencePipeline.java:88)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.addViewsAndCache(BasicAnnotatorService.java:371)
	at edu.illinois.cs.cogcomp.pipeline.main.SentencePipelineTest.testSentencePipeline(SentencePipelineTest.java:90)
