### ISSUE TITLE
Exception when using md

### ISSUE THREAD

**Issue by b29308188** [CogComp/cogcomp-nlp#539]
I was trying to use mention detector in the cross-lingual-wikifier by 
```
MentionAnnotator mentionAnnotator = new MentionAnnotator();
mentionAnnotator.addView(ta);
```

It then gives me an exception of 
```
Exception in thread "main" java.lang.IllegalArgumentException: View POS not found
	at edu.illinois.cs.cogcomp.core.datastructures.textannotation.AbstractTextAnnotation.getView(AbstractTextAnnotation.java:134)
	at org.cogcomp.md.BIOFeatureExtractor.getPOSFeatures(BIOFeatureExtractor.java:147)
	at org.cogcomp.md.LbjGen.POS_Features.classify(POS_Features.java:53)
	at org.cogcomp.md.LbjGen.bio_classifier_nom$$1.classify(bio_classifier_nom$$1.java:68)
	at edu.illinois.cs.cogcomp.lbjava.learn.Learner.getExampleArray(Learner.java:731)
	at org.cogcomp.md.LbjGen.bio_classifier_nom.getExampleArray(bio_classifier_nom.java:1104)
	at edu.illinois.cs.cogcomp.lbjava.learn.Learner.featureValue(Learner.java:499)
	at org.cogcomp.md.LbjGen.bio_classifier_nom.featureValue(bio_classifier_nom.java:181)
	at org.cogcomp.md.LbjGen.bio_classifier_nom.discreteValue(bio_classifier_nom.java:192)
	at org.cogcomp.md.BIOTester.joint_inference(BIOTester.java:260)
	at org.cogcomp.md.MentionAnnotator.addView(MentionAnnotator.java:186)
```

So I add the POS view by myself with curator, but it gives me another exception:
 
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.cogcomp.md.BIOFeatureExtractor.getPOSFeatures(BIOFeatureExtractor.java:153)
	at org.cogcomp.md.LbjGen.POS_Features.classify(POS_Features.java:53)
	at org.cogcomp.md.LbjGen.bio_classifier_nom$$1.classify(bio_classifier_nom$$1.java:68)
	at edu.illinois.cs.cogcomp.lbjava.learn.Learner.getExampleArray(Learner.java:731)
	at org.cogcomp.md.LbjGen.bio_classifier_nom.getExampleArray(bio_classifier_nom.java:1104)
	at edu.illinois.cs.cogcomp.lbjava.learn.Learner.featureValue(Learner.java:499)
	at org.cogcomp.md.LbjGen.bio_classifier_nom.featureValue(bio_classifier_nom.java:181)
	at org.cogcomp.md.LbjGen.bio_classifier_nom.discreteValue(bio_classifier_nom.java:192)
	at org.cogcomp.md.BIOTester.joint_inference(BIOTester.java:260)
	at org.cogcomp.md.MentionAnnotator.addView(MentionAnnotator.java:186)
```

illinois-core-utilities and llinois-pos are included in my pom.xml file.

**Comment by b29308188** [comment]
It works fine when I use POSAnnotator instead of curator.

**Comment by danyaljj** [comment]
You have to add POS to your TextAnnotation object before running it through mention detection.
