### ISSUE TITLE
NESim NoSuchMethodError

### ISSUE THREAD

**Issue by sanjayss34** [CogComp/cogcomp-nlp#618]

**Comment by sanjayss34** [comment]
Hi,

I am trying to install and use the similarity package to use NESim. However, when I call the constructor for NESim() I get the following error:
```
Exception in thread "main" java.lang.NoSuchMethodError: edu.illinois.cs.cogcomp.core.io.IOUtils.lsResources(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/List;
	at edu.illinois.cs.cogcomp.nesim.io.MappingReader.getReader(MappingReader.java:51)
	at edu.illinois.cs.cogcomp.nesim.io.MappingReader.readListMapping(MappingReader.java:91)
	at edu.illinois.cs.cogcomp.nesim.data.AcronymManager.readAcronymFile(AcronymManager.java:293)
	at edu.illinois.cs.cogcomp.nesim.data.AcronymManager.<init>(AcronymManager.java:38)
	at edu.illinois.cs.cogcomp.nesim.compare.EntityComparison.<init>(EntityComparison.java:56)
	at edu.illinois.cs.cogcomp.sim.NESim.<init>(NESim.java:25)
	at test.main(test.java:6)
```
I first ran "mvn compile" on the whole cogcomp-nlp directory. My code compiled fine, and this error occurred at runtime. I would appreciate any help that you can provide. Thank you!

**Comment by danyaljj** [comment]
Can you try running after `mvn install -Dmaven.test.skip=true`? (instead of `mvn compile`)

**Comment by sanjayss34** [comment]
This worked. Thank you!
